[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_toy = "2FYV28WPRyd6qD6k62BsB2kf6AJ8UBUpnNTR5J2h37da"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
